### ISSUE TITLE
Change in description

### ISSUE THREAD

**Issue by mboelen** [softasap/sa-secure-audit-lynis#1]
Thanks for creating this work to deploy Lynis. The description of the project has a small error in that it mentions Lynis as "freeware".

> Lynis is a security auditing tool for UNIX derivatives. Freeware part of the cisofy product. Assists with compliance testing (HIPAA/ISO27001/PCI DSS) and system hardening. Agentless

Can you replace the part of "freeware" (and after that), into:

> Open source software, part of CISOfy's Lynis Enterprise product.

**Comment by Voronenko** [comment]
@mboelen Thank you for your input. Description was corrected.
